#  01. Data Understanding & Initial Inspection
## Objectives:
- Load `syndelay_v1.csv` dataset.
- Inspect row/column counts, data types, missing values, and high-level statistics.
- Verify target distribution (`label`).

In [3]:
# importing libraries

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("/home/patel-krish/anaconda3/BrainyBeam/SuplyChainDelay/data/syndelay_v1.csv")

In [7]:
df

,payment_type,profit_per_order,sales_per_customer,category_id,category_name,customer_city,customer_country,customer_id,customer_segment,customer_state,...,order_region,order_state,order_status,product_card_id,product_category_id,product_name,product_price,shipping_date,shipping_mode,label
0,PAYMENT,-32.924488,278.950000,38,Kids' Golf Clubs,Caguas,Puerto Rico,12446.5625,Corporate,PR,...,Caribbean,Martinique,PENDING_PAYMENT,858,38,GolfBuddy VT3 GPS Watch,129.99,42177.500,Second Class,2
1,DEBIT,107.874500,263.980000,17,Cleats,Caguas,Puerto Rico,7782.0170,Corporate,PR,...,East Africa,Copperbelt,COMPLETE,365,17,Perfect Fitness Perfect Rip Deck,59.99,42502.390,Same Day,1
2,PAYMENT,35.770718,109.650130,17,Cleats,Caguas,Puerto Rico,7378.1113,Consumer,PR,...,West Asia,Ankara,PENDING_PAYMENT,365,17,Perfect Fitness Perfect Rip Deck,59.99,42951.266,Standard Class,0
3,PAYMENT,43.587560,113.090000,18,Men's Footwear,Caguas,Puerto Rico,1448.6765,Consumer,PR,...,Central America,Francisco Morazan,PENDING_PAYMENT,403,18,Nike Men's CJ Elite 2 TD Football Cleat,129.99,42181.900,Second Class,2
4,PAYMENT,49.804802,191.980900,9,Cardio Equipment,Madison,EE. UU.,5123.5254,Corporate,WI,...,Central America,Leon,PENDING_PAYMENT,191,9,Nike Men's Free 5.0+ Running Shoe,99.99,42632.820,Standard Class,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155483,TRANSFER,-57.828900,163.990000,29,Shop By Sport,Milford,EE. UU.,10456.0340,Consumer,CT,...,Central America,Mexico,PROCESSING,627,29,Under Armour Girls' Toddler Spine Surge Runni,39.99,42715.277,First Class,2
155484,DEBIT,125.350204,392.006440,45,Fishing,Saint Louis,EE. UU.,5690.0977,Consumer,MO,...,Southeast Asia,Riau,COMPLETE,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.98,42411.030,Second Class,1
155485,TRANSFER,49.595863,104.378204,67,DVDs,Chicago,EE. UU.,11397.8750,Consumer,IL,...,Southern Europe,Apulia,PENDING,1354,67,DVDs,29.99,42037.516,Standard Class,2
155486,CASH,80.183090,293.980000,43,Camping & Hiking,Provo,EE. UU.,7845.9480,Consumer,UT,...,Southern Europe,Lombardy,CLOSED,957,43,Diamondback Women's Serene Classic Comfort Bi,299.98,42656.656,Second Class,2
155487,CASH,121.221060,395.980000,45,Fishing,Tallahassee,EE. UU.,2545.1620,Consumer,FL,...,Western Europe,Nord-Pas-de-Calais-Picardy,CLOSED,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.98,42525.867,Standard Class,0

In [8]:
df.shape

(155488, 41)

In [10]:
df.dtypes

payment_type                 object
profit_per_order            float64
sales_per_customer          float64
category_id                   int64
category_name                object
customer_city                object
customer_country             object
customer_id                 float64
customer_segment             object
customer_state               object
customer_zipcode            float64
department_id                 int64
department_name              object
latitude                    float64
longitude                   float64
market                       object
order_city                   object
order_country                object
order_customer_id           float64
order_date                  float64
order_id                    float64
order_item_cardprod_id      float64
order_item_discount         float64
order_item_discount_rate    float64
order_item_id               float64
order_item_product_price    float64
order_item_profit_ratio     float64
order_item_quantity         float64
sales                       float64
order_item_total_amount     float64
order_profit_per_order      float64
order_region                 object
order_state                  object
order_status                 object
product_card_id               int64
product_category_id           int64
product_name                 object
product_price               float64
shipping_date               float64
shipping_mode                object
label                         int64
dtype: object

In [11]:
df.isnull().any()

payment_type                False
profit_per_order            False
sales_per_customer          False
category_id                 False
category_name               False
customer_city               False
customer_country            False
customer_id                 False
customer_segment            False
customer_state              False
customer_zipcode            False
department_id               False
department_name             False
latitude                    False
longitude                   False
market                      False
order_city                  False
order_country               False
order_customer_id           False
order_date                  False
order_id                    False
order_item_cardprod_id      False
order_item_discount         False
order_item_discount_rate    False
order_item_id               False
order_item_product_price    False
order_item_profit_ratio     False
order_item_quantity         False
sales                       False
order_item_total_amount     False
order_profit_per_order      False
order_region                False
order_state                 False
order_status                False
product_card_id             False
product_category_id         False
product_name                False
product_price               False
shipping_date               False
shipping_mode               False
label                       False
dtype: bool

In [17]:
df.describe()

,profit_per_order,sales_per_customer,category_id,customer_id,customer_zipcode,department_id,latitude,longitude,order_customer_id,order_date,...,order_item_profit_ratio,order_item_quantity,sales,order_item_total_amount,order_profit_per_order,product_card_id,product_category_id,product_price,shipping_date,label
count,155488.000000,155488.000000,155488.000000,155488.000000,1.554880e+05,155488.000000,155488.000000,155488.000000,155488.000000,155488.000000,...,155488.000000,155488.000000,155488.000000,155488.000000,155488.000000,155488.000000,155488.000000,155488.000000,155488.000000,155488.000000
mean,22.625080,181.098027,31.642847,6681.724789,2.086163e+04,5.433641,29.784330,-84.722127,6642.201590,42534.882311,...,0.126187,2.125025,201.818054,181.253691,23.134572,687.903813,31.642847,139.148537,42538.406750,1.340766
std,119.818361,113.480905,15.597621,4112.453329,6.539288e-08,1.627307,9.695576,20.402017,4085.771174,302.327634,...,0.457384,1.445474,126.662042,114.731803,97.974173,335.986891,15.597621,133.748436,302.326223,0.834877
min,-4274.980000,7.780167,2.000000,2.000000,2.086163e+04,2.000000,-33.937553,-158.025990,2.000000,42005.016000,...,-2.750000,1.000000,9.990000,7.492500,-3824.466045,19.000000,2.000000,9.990000,42005.652000,0.000000
25%,7.568531,105.570935,18.000000,3297.375900,2.086163e+04,4.000000,18.266945,-97.668050,3272.024200,42274.645750,...,0.080000,1.000000,119.980000,103.992000,7.425000,403.000000,18.000000,50.000000,42278.233000,1.000000
50%,32.682004,165.948080,29.000000,6417.069250,2.086163e+04,5.000000,33.362042,-78.744316,6397.487550,42539.712500,...,0.270000,1.000000,199.920000,163.983600,32.172525,627.000000,29.000000,59.990000,42543.318000,2.000000
75%,64.366681,245.980000,45.000000,9735.472250,2.086163e+04,7.000000,39.109177,-66.370580,9672.004250,42787.679750,...,0.360000,3.000000,299.950000,245.983600,64.796760,1004.000000,45.000000,199.990000,42791.151500,2.000000
max,805.540160,1939.990000,76.000000,20757.000000,2.086163e+04,12.000000,48.781933,115.040000,20757.000000,43131.984000,...,0.500000,5.000000,1999.990000,1858.859300,799.931238,1363.000000,76.000000,1999.990000,43137.984000,2.000000

In [16]:
df["customer_zipcode"] = df["customer_zipcode"].median()

In [18]:
df['label'].value_counts(normalize=True) * 100

label
2    57.695128
0    23.618543
1    18.686329
Name: proportion, dtype: float64